name: Test seal

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - 'seal/**'
  push:
    branches: [main]
    paths:
      - 'seal/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./test_seal.sh -v
        working-directory: seal
