name: Test pomodoro

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'pomodoro/**'
  push:
    paths:
      - 'pomodoro/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./test_pomodoro.sh -v
        working-directory: pomodoro
